name: build-jar

on:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Run tests"
        run: gradle test
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Attempt compilation"
        run: gradle build
