name: build-jar

on:
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install jfx
        run: sudo apt-get install -y openjfx

      - name: "Run tests"
        run: gradle test

      - name: Attempt compilation
        run: gradle build
